spring:
  application:
    name: one-more
  datasource:
    url: jdbc:postgresql://localhost:5432/one_more
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false

logging:
  level:
    root: WARN
  file:
    name: one-more-logs
    path: /